push_image:
  script:
    - docker login -u $USERNAME -p $PASSWORD
    - docker tag pyapp:latest $USERNAME/myapp:latest
    - docker push $USERNAME/myapp:latest
  tags:
    - localshell
    - localrunner






#variables:
  #NAME: 'John'
  #MESSAGE: 'How are you'

#display_message:
  #variables:
    #NAME: 'Mark'
  #script:
    #- echo "Hello $NAME, $MESSAGE"