stages:
  - push
  - display


push_image:
  stage: push
  script:
    - docker login -u $USERNAME -p $PASSWORD
    - docker tag pyapp:latest $USERNAME/myapp:latest
    - docker push $USERNAME/myapp:latest
  tags:
    - localshell
    - localrunner

display_message:
  stage: display
  script:
    - echo "Hi, $USERNAME"





#variables:
  #NAME: 'John'
  #MESSAGE: 'How are you'

#display_message:
  #stage: display
  #variables:
  #NAME: 'John'
  #MESSAGE: 'How are you'
  #script:
    #- echo "Hello $NAME, $MESSAGE"